"""
Configuration constants for Jour 3: E2EE Chat System
"""

# Server
SERVER_HOST = '0.0.0.0'
SERVER_PORT = 5001
SERVER_LISTEN_BACKLOG = 5
SERVER_SOCKET_TIMEOUT = 1.0

# Client
CLIENT_TIMEOUT = 5.0
BUFFER_SIZE = 4096

# Cryptography - Symmetric (AES from Jour 2)
ENCRYPTION_ALGORITHM = 'AES-256-CBC'
HMAC_ALGORITHM = 'SHA256'
PBKDF2_ITERATIONS = 480000
PBKDF2_HASH = 'SHA256'
SALT_SIZE = 16
AES_KEY_SIZE = 32
AES_IV_SIZE = 16

# Cryptography - Asymmetric (RSA for Jour 3)
RSA_KEY_SIZE = 2048
RSA_PUBLIC_EXPONENT = 65537
RSA_PADDING = 'OAEP'
RSA_HASH_ALGORITHM = 'SHA256'

# Signatures
SIGNATURE_ALGORITHM = 'RSA-PSS'
SIGNATURE_HASH = 'SHA256'

# Message Protocol
MESSAGE_TYPE_AUTH = 'AUTH'
MESSAGE_TYPE_PUBLIC_KEY = 'PUBLIC_KEY'
MESSAGE_TYPE_MSG = 'MSG'
MESSAGE_TYPE_USER_LIST = 'USER_LIST'
MESSAGE_TYPE_E2EE_SETUP = 'E2EE_SETUP'

# Key management
KEY_STORAGE_DIR = '~/.crypto_vibeness'
PRIVATE_KEY_EXTENSION = '.priv'
PUBLIC_KEY_EXTENSION = '.pub'

# Session management
SESSION_TIMEOUT = 3600  # 1 hour
MAX_MESSAGE_SIZE = 10000
